name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --stack-name nodejs-ha-stack \
          --template-file cloudformation/infra.yml \
          --parameter-overrides KeyName=YOUR_KEY_PAIR_NAME \
          --capabilities CAPABILITY_IAM
